### ISSUE TITLE
可以简要在文档中说明一下如何移植linux吗？

### ISSUE THREAD

**Issue by KleinSteven** [LoveLonelyTime/Bergamot#1]

**Comment by LoveLonelyTime** [comment]
@KleinSteven The main thing is actually to write a device tree(.dts) and make rootfs. I will write this document in the near future. Thanks.

**Comment by LoveLonelyTime** [comment]
@KleinSteven [Run linux](https://lovelonelytime.github.io/Bergamot-doc/docs/example/run-linux) is available.

**Comment by KleinSteven** [comment]
> @KleinSteven [Run linux](https://lovelonelytime.github.io/Bergamot-doc/docs/example/run-linux) is available.

Thank you for the blog on Linux porting! It's truly helpful.
